version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: omarbh1501/stage_repo:${BUILD_NUMBER}
    ports:
      - "8081:8081"
    environment:
      
      - NODE_ENV=production
